name: Update blog posts to README

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://blog.starskim.cn/feed/
          readme-section: posts
